site_name: Hevs ☁️ notes
theme:
  name: material
  favicon: images/favicon2.png
  #custom_dir: overrides
  features:
    - content.code.copy
    - content.tabs.link
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: hevs-material
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  icon:
    # This is the top bar
    logo: octicons/cloud-24
  highlightjs: true
  hljs_languages:
      - yaml
extra_css:
  - stylesheets/extra.css
extra: 
  social:
    - icon: octicons/rocket-16
      link: https://hevs.cloud
plugins:
  - blog:
      post_url_format: "{categories}/{slug}"
      authors: false
      archive_toc: true
      categories_toc: true
  - search
  - tags
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences # Content tabs
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - md_in_html
  - attr_list # Stylesheets tokens/types of strings: https://pygments.org/docs/tokens/#literals
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - footnotes